all: run Gene_userInfo

run: *.cpp *.h
		g++ run.cpp -Wall -std=c++11 -O3 ../dSFMT/dSFMT.c -o run

Gene_userInfo: *.cpp *.h
		g++ Gene_userInfo.cpp -Wall -std=c++11 -O3 ../dSFMT/dSFMT.c -o Gene_userInfo